#!/usr/bin/env bash
# Script to display information about subdomains

display_subdomain_info() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dig_output=$(dig "$sub.$domain" +short)
        if [ -z "$dig_output" ]; then
            echo "No records found for $sub.$domain"
        else
            record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
            destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $5}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

display_subdomain_info "$1" "$2"
