#!/usr/bin/env bash
# This script displays information about subdomains for a given domain

function get_subdomain_info {
    local domain=$1
    local subdomain=$2
    local result=$(dig +short ${subdomain}.${domain})
    if [[ -n $result ]]; then
        echo "The subdomain ${subdomain} is an A record and points to ${result}"
    else
        echo "The subdomain ${subdomain} does not exist or has no A record"
    fi
}

domain=$1
subdomain=$2

if [[ -z $domain ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

if [[ -z $subdomain ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_subdomain_info $domain $sub
    done
else
    get_subdomain_info $domain $subdomain
fi
