#!/usr/bin/env bash
# This script fetches DNS information for given subdomains of a domain

get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    record=$(dig "${subdomain}.${domain}" +short)
    if [[ -n "$record" ]]; then
        echo "The subdomain ${subdomain} is an A record and points to ${record}"
    else
        echo "No A record found for ${subdomain}.${domain}"
    fi
}

if [[ -z "$1" ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1
if [[ -n "$2" ]]; then
    subdomain=$2
    get_subdomain_info "$domain" "$subdomain"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        get_subdomain_info "$domain" "$subdomain"
    done
fi
