#!/usr/bin/env bash
# Setup script for a new Ubuntu machine to run Nginx
# It listens on port 80 and serves a "Hello World" page

printf "Initiating Nginx installation and update process.\n"
sudo apt-get update -y > /dev/null && sudo apt-get install -y nginx > /dev/null

printf "\nApplying configurations and permissions.\n"

# Begin Nginx service
sudo systemctl start nginx

# Update firewall rules to allow Nginx traffic
sudo ufw allow 'Nginx HTTP' > /dev/null

# Adjust ownership and permissions for web content directory
sudo chown -R $USER:$USER /var/www/html
sudo find /var/www -type d -exec chmod 755 {} \;

# Safeguard original index file and create a new one
sudo mv /var/www/html/index.nginx-debian.html{,.backup}

# Inject "Hello World!" into the new index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Reload Nginx to apply new settings
sudo systemctl reload nginx

printf "\nSetup complete. ✔️\n"
