#!/usr/bin/env bash
# Configures Nginx to display a custom 404 page

# Check if Nginx is installed, install if it's not
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
echo 'server {
    listen 80 default_server;
    server_name _;

    root /var/www/html;

    error_page 404 /custom_404.html;

    location / {
        try_files $uri $uri/ =404;
    }
}' | sudo tee /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo nginx -t && sudo service nginx reload
