#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP header named X-Served

# Install Nginx if it's not already installed
apt-get update
apt-get install -y nginx

# Configure Nginx to add the custom header
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
systemctl restart nginx
