#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

if [ $# -eq 0 ]
then
	  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  else
	    ping -c 5 "$1"
fi#!vgbin/bash

# Check if an IP address argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the specified IP address 5 times
ping -c 5 "$1
