#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely with 'I am invincible!!!' upon receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
