#!/usr/bin/env bash
# This script checks if the 'school' file exists, if it's empty or not, and if it's a regular file.

filename="school"

if [[ -e $filename ]]
then
    echo "school file exists"
    
    if [[ -s $filename ]]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [[ -f $filename ]]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
